title: Plain language
description: A paper about the usage of plain language in technical communication and how it can improve readability and usability 
theme: just-the-docs
url: https://godai78.github.io/plain-language/
aux_links:
  Template Repository: https://github.com/godai78/plain-language
search_enabled: true
nav_enabled: true
footer_content: "All materials licensed CC-BY-NC-SA 4.0 Bartek Biedrzycki 2025"
